"""initial schema

Revision ID: a74d67003c8f
Revises: 
Create Date: 2026-09-03 10:36:26.862279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74d67003c8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unas_customer_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_name_cache', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_customers_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_loyalty_customers_unas_customer_id'), ['unas_customer_id'], unique=True)

    op.create_table('stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('raw_payload_masked', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('verify_status', sa.String(length=20), nullable=False),
    sa.Column('process_status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_event_key'), ['event_key'], unique=True)

    op.create_table('registers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('external_receipt_id', sa.String(length=200), nullable=True),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('register_id', sa.String(length=36), nullable=True),
    sa.Column('cashier_user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('reversed_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('unas_response_ref', sa.String(length=200), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['loyalty_customers.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.ForeignKeyConstraint(['reversed_transaction_id'], ['loyalty_transactions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_loyalty_tx_idempotency_key')
    )
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_transactions_idempotency_key'), ['idempotency_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_transactions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_loyalty_transactions_customer_id'))

    op.drop_table('loyalty_transactions')
    op.drop_table('users')
    op.drop_table('registers')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_event_key'))

    op.drop_table('webhook_events')
    op.drop_table('stores')
    with op.batch_alter_table('loyalty_customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_customers_unas_customer_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_customers_token_hash'))

    op.drop_table('loyalty_customers')
    # ### end Alembic commands ###
